cache: bundler
env:
  global:
    secure: "G0LDGrupZ+RAFzoPwd6bjfrWfwoU/V9RTswQXIUNmi640rW/CP86a8F9hQcAXdUwy7Ag1cwmlEEv2JDDbLopQdNvkh8B7M3PSIpmJWlBsj+UPMMcCz04oYiQB3G6xgYb4xeuY6cNqxiY2rTJMHlfUfTlSJf1Z0dh6hAS3alHpGw="
  matrix:
    - RAKE_TASK=cucumber
    - RAKE_TASK=spec
language: ruby
matrix:
  fast_finish: true
  include:
    - rvm: 2.1
      env: RAKE_TASK=yard
rvm:
- 2.1
script: "bundle exec rake $RAKE_TASK"
sudo: false
