env:
  global:
    secure: "G0LDGrupZ+RAFzoPwd6bjfrWfwoU/V9RTswQXIUNmi640rW/CP86a8F9hQcAXdUwy7Ag1cwmlEEv2JDDbLopQdNvkh8B7M3PSIpmJWlBsj+UPMMcCz04oYiQB3G6xgYb4xeuY6cNqxiY2rTJMHlfUfTlSJf1Z0dh6hAS3alHpGw="
  matrix:
    - RAKE_TASK=cucumber
    - RAKE_TASK=spec
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
    # cucumber keeps hitting job time limit of 50 minutes
    - rvm: rbx-2.2
  fast_finish: true
  # documentation coverage is not influenced by ruby version, but the dependencies differ for MRI and JRuby, so
  # rake yard for both.
  include:
    - rvm: 2.1
      env: RAKE_TASK=yard
    - rvm: jruby
      env: RAKE_TASK=yard
rvm:
- 1.9.3
- 2.0
- 2.1
- ruby-head
- jruby
- rbx-2.2
script: "bundle exec rake $RAKE_TASK"
